### PR TITLE
#770 Hartshorn Scripting Language (HSL) with condition support

### LINKED ISSUE #770: Expression/scripting support for conditions
### Related problem

Any condition requires two things: a `RequiresCondition` stereotype, and a `Condition` implementation. While this is useful for common conditions, such as `RequiresClass` and `RequiresActivator`, this is not preferable for specific conditions which may only appear once or twice throughout an application. 

### Requested feature

Allow the use of expressions/scripting inside a `RequiresExpression` condition, which evaluates a specific custom expression. This would allow for near endless flexibility for end-users. This should support a variety of standard features, and should be somewhat equal to Java's syntax to be recognizable for developers.

Exact specifications are open for discussion. This issue will quickly be followed up with a related proposal PR, where active drafts will be demonstrated.

### PR DESCRIPTION
**Pull request by GuusLieben**
# Description
## Introduction
When first implementing the condition matcher API for (among others) providers, an important question arose; how do we handle complex single-use requirements? Any condition requires two things: a `RequiresCondition` stereotype, and a `Condition` implementation. While this is useful for common conditions, such as `RequiresClass` and `RequiresActivator`, this is not preferable for specific conditions which may only appear once or twice throughout an application. 

A solution which can be seen across other frameworks is the use of scripting- and/or expression language solutions. This allows the use of expressions/scripting inside a condition, which evaluates a specific custom expression. Which would allow for near endless flexibility for end-users.

The proposed changes introduce a custom interpreted language which integrates with Hartshorn to allow us to offer dynamic conditions to end-users. The syntax is inspired by Java, with minor influences from JavaScript. In the paragraphs below I'll introduce the language syntax, and finalize this PR with reference usages. To introduce the syntax I'll first present the available expressions, followed by possible statements.

Important to note is that semicolons are completely optional in HSL. The examples below may or may not use statements ending with semicolons, without specific notice or reason.

Notes:
✅: Section is done/ready for review
♾️: Section is still being written

#### Variables ✅
Variables are defined using the `var` keyword, followed by their name. Variables can be defined without assigning an initial value. Variables are not typed, and may be any type.
```js
var name = "Foo";
```
```js
var name;
name = "Foo";
```

#### Variable properties ✅
As variables are not typed by default, any instance variable can have properties set on it dynamically. This only goes for instance variables, and does not apply to literals like `String`s. This also does not apply to external typed object instances.
```js
class Object {}
var user = Object();
user.age = 12;
```

#### Literals ✅
Literals are tokens that do not hold a specific value, but do offer a specific representation. There are five types of literals:
1. Identifiers: An identifier can be the name of a variable, function, or class. For example, in `var name`, `name` is an identifier.
2. String: Strings represent a piece of text, for example `"Hello world!"` is a valid string.
3. Number: Numbers can represent either whole or decimal numbers, and are handled as doubles by default.
4. Char: Chars represent single characters, for example `'a'` is a valid char.
5. EOF: EOF tokens cannot be typed in a script, and are added by the lexer to represent the end of a script.

#### Array accessing and modification ✅
Arrays are simple collections of objects. Arrays in HSL follow the familiar syntax to get and set values in the array, and require their length to be defined when first assigned. Arrays are initialized using array literals by wrapping zero or more values in `[]`, and can hold any object type.
```js
var foo = [null, null, null];
foo[2] = "Bar";
```
```js
var bar = foo[2]; // "Bar"
var baz = foo[3]; // null
```

It is also possible to repeat arrays, expanding their size automatically.
```js
var foo = [null] * 3; // [null, null, null]
```

#### Logical operations ✅
HSL offers several logical operations to evaluate conditions. Logical conditions can be applied to any _truthy_ or _falsey_ value. The value of a truthy value is determined as follows:
`null -> false`
`boolean instance -> value`
`not null -> true`

Logical operators are:
- `||` (double pipe): Two pipes represent an OR operation. Only one condition needs to be `true`, or the output is `false`. 
    - `true || true`  ->  `true`
    - `true || false`  ->  `true`
    - `false || false`  ->  `false`
- `&&` (double ampersand): Two ampersands represent an AND operation. All conditions should be `true`, or the output is `false`.
    - `true && true`  ->  `true`
    - `true && false`  ->  `false`
    - `false && false`  ->  `false`
- `^` (caret): A single caret represents an XOR (exclusive OR) operation. Only one condition should be `true`, or the output is `false`. If more than one condition is `true`, the result is `false`.
    - `true ^ true`  ->  `false`
    - `true ^ false`  ->  `true`
    - `false ^ false`  ->  `false`

#### Binary operations ✅
HSL supports all standard binary operations and associated operators. 
##### Arithmetic operations ✅
- `+` (PLUS): Add two number values together (e.g. `1+2 = 3`)
- `-` (MINUS): Substract the second number from the first number (e.g. `4-3 = 1`)
- `*` (MULTIPLY): Multiply two number values (e.g. `2*3 = 6`)
- `/` (DIVIDE): Divide the first number by the second number (e.g. `6/2 = 3`)
- `%` (MODULO): Returns the remainder after the first number is divided by the second number (e.g. `5 % 2 = 1`)

##### Condition operations ✅
- `>` (GREATER): Is the left value greater than the right value
    - `1 > 2` -> `false`
    - `2 > 2` -> `false`
    - `2 > 1` -> `true`
- `>=` (GREATER OR EQUAL): Is the left value greater than, or equal to the right value
    - `1 > 2` -> `false`
    - `2 > 2` -> `true`
    - `2 > 1` -> `true`
- `<` (LESS): Is the left value less/smaller than the right value
    - `1 < 2` -> `true`
    - `2 < 2` -> `false`
    - `2 < 1` -> `false`
- `<=` (LESS OR EQUAL): Is the left value less/smaller than, or equal to the right value
    - `1 <= 2` -> `true`
    - `2 <= 2` -> `true`
    - `2 <= 1` -> `false`
- `==` (EQUAL): Is the left value equal to, or the same as the right value
    - `1 == 2` -> `false`
    - `2 == 2` -> `true`
    - `"foo" == "bar"` -> `false`
    - `"foo" == "foo"` -> `true`
- `!=` (NOT EQUAL): Is the left value not equal, or the same as the right value
    - `1 != 2` -> `true`
    - `2 != 2` -> `false`
    - `"foo" != "bar"` -> `true`
    - `"foo" != "foo"` -> `false`

##### Special scenarios ✅
`+` (PLUS) also supports a variety of other combinations, which are handled as follows:
- `number + number` -> sum of number (`1+1 = 2`)
- `string + string` -> concatenated string (`"foo" + "bar" = "foobar"`)
- `char + char` -> concatenated string (`'a' + 'b' = "ab"`)
- `char + number` -> sum of character's integer value and number (`'a' + 2` = 97 + 2 = 99`)
- `number + char` -> sum of character's integer value and number (`2 + 'a' = 2 + 97 = 99`)

#### Unary operations ✅
Alongside binary operations, several unary operations are also supported:
- `-var` (NEGATIVE): Inverts a number to its negative counterpart. If the number is already negative, it'll become positive.
    - `1` -> `-1`
    - `-1` -> `1`
- `++var` (INCREMENT and GET): Increments the value of a number by one. The result of the operation is the incremented value.
    - `1` -> `2`
    - `10` -> `11`
- `--var` (DECREMENT and GET): Decrements the value of a number by one. The result of the operation is the decreased value.
    - `1` -> `0`
    - `10` -> `9`
- `!var` (INVERT CONDITION): Inverts/negates a (truthy) condition. If the value is a `boolean` type, it will negate the value. If the value is another type, it will negate the thruthy-ness of the value.
    - `true` -> `false`
    - `false` -> `true`
    - `null` = `false` -> `true`
    - `"value"` = `true` -> `false`
- `~var` (COMPLEMENT): Bitwise complement, changes binary digits 1 to 0 and 0 to 1
    - `35` = `00100011` (binary) -> `11011100` (binary) = `-36`

#### Bitwise operations ✅
HSL offers several bitwise operators, which can be applied to any pair of numbers.
- `>>` (SIGNED SHIFT RIGHT): Shifts the binary value of a number `n` steps to the right (`n` being the right side value of the operation) Uses the sign bit to fill trailing positions. If the number is positive then 0 will be used to fill trailing positions, if the number is negative then 1 will be used to fill trailing positions.
    - `60` = `0000 0000 0000 0000 0000 0000 0011 1100`
       - `60 >> 1` = `0000 0000 0000 0000 0000 0000 0001 1110`
    - `-60` = `1111 1111 1111 1111 1111 1111 1100 0100`
       - `-60 >> 1` = `1111 1111 1111 1111 1111 1111 1110 0010`
- `>>>` (UNSIGNED SHIFT RIGHT): Similar to `>>`, except that it does not use the sign bit to fill trailing positions. Instead it always fills trailing positions with 0.
    - `60` = `0000 0000 0000 0000 0000 0000 0011 1100`
       - `60 >>> 1` = `0000 0000 0000 0000 0000 0000 0001 1110`
    - `-60` = `1111 1111 1111 1111 1111 1111 1100 0100`
       - `-60 >>> 1` = `0111 1111 1111 1111 1111 1111 1110 0010`
- `<<` (SIGNED SHIFT LEFT): Similar to right shifting, except that it shifts to the left. Trailing positions are always filled with 0.
    - `60` = `0000 0000 0000 0000 0000 0000 0011 1100`
       - `60 << 1` = `0000 0000 0000 0000 0000 0000 0111 1000`
    - `-60` = `1111 1111 1111 1111 1111 1111 1100 0100`
       - `-60 << 1` = `1111 1111 1111 1111 1111 1111 1000 1000`
- `&` (BITWISE AND): Yields the bit by bit AND value of the input values. If both bits are 1, 1 is returned, else 0 is returned.
    - `5` = `0101`, `7` = `0111`
    - `5 & 7` = `0101` = `5`
- `|` (BITWISE OR): Yields the bit by bit OR value of the input values. If either of the bits is 1, 1 is returned, else 0 is returned.
    - `5` = `0101`, `7` = `0111`
    - `5 | 7` = `0111` = `7`
- `^` (BITWISE XOR): Yields the bit by bit XOR value of the input values. If the bits are different, 1 is returned, else 0 is returned.
    - `5` = `0101`, `7` = `0111`
    - `5 ^ 7` = `0010` = `2`

#### Elvis and ternary operators ✅
HSL supports two types of conditional shorthand operators; elvis and ternary operators. With the ternary operator it is possible to obtain a specific value based on a given condition. The operator starts with the condition, followed by the value if `true`, and finally the value if `false`.
- `condition ? ifTrue : ifFalse`
- `true ? "foo" : "bar"` -> `"foo"`
This also supports truthy values, allowing specific values to be obtained based on the presence of another:
- `null ? "foo" : "bar"` -> `"bar"`
- `"baz" ? "foo" : "bar"` -> `"foo"`

A further improvement of this is the elvis operator. Here the `ifTrue` value is equal to the condition's value. This is especially useful for truthy values.
- `condition ?: ifFalse`
- `true ?: false` -> `true`
- `null ?: "bar"` -> `"bar"`
- `"foo" ?: "bar"` -> `"foo"`

#### Grouping ✅
Basic grouping support is present, allowing for finer control of statements and expressions. A group can be used anywhere an expression could be used. A group can contain one or more expressions, and will be evaluated on its own. The result of a group expression will then be provided as a single value.
- `3 * (3 + 3)` = `3 * 6` = `18`
- `true || (true && false)` = `true || false` = `true`

Combining this with other operators:
- `3 + (3 + 3) == 18 ?: "value is " + (3 + (3 + 3))`

#### Arrays ✅
Arrays are the primary primitive form of collections in HSL, which can be declared in several ways. Each option is explained below.

All array declarations can be selected, modified, and repeated. Selection and modification use indexed selectors, starting at index=0.
```js
var array = [1,2,3];
var first = array[0]; // Selection -> 1
array[0] = 12; // Modification -> [12,2,3]
var secondArray = array * 2 // Repeating -> [12, 2 ,3 , 12, 2, 3]
```

##### Literals ✅
Array literals are the most basic form of array declarations. An array literal is a collection of expressions wrapped between `[]`, and separated by commas. Each expression can be any type of expression, whether that is a variable, literal, or complex expression.
```js
var a1 = [1,2,3];

var num = 12;
var a2 = [num, 2, 3]; // [12, 2, 3]

var a3 = [2*3, 2+4, 2-4]; // [6, 6, -2]
```

##### Comprehension ✅
Array comprehension allows the use of existing iterables to create a new array from existing data. All expressions in all comprehension forms allow the element to be used using the name indicated in the expression. 

###### Standard ✅
A standard array comprehension consists of a single expression which can be performed for each object in the given collection. For example, increasing all numbers in an array by one.
```js
var array = [1,2,3];
var copyPlusOne = [x + 1 for x in array]; // [2,3,4]
```

###### Conditional ✅
Conditional comprehensions allow for an additional filter to be applied to each element, to indicate whether or not the value should be processed and included in the new array. If the condition yields `false`, the element will not be included in the new array.
```js
var array = [1,2,3];
var copyWithoutTwo = [x for x in array if x != 2]; // [1,3]
```

###### Fallback values ✅
Conditional array comprehensions also allow a fallback value to be provided when the condition yields `false`, instead of skipping the value. 
```js
var array = [1,2,3];
var copyWithFourForTwo = [x for x in array if x != 2 else 4]; // [1,4,3]
```

#### Variable declaration and assignment ✅
Variables in HSL are untyped by default (some exceptions exist for external types, but that will be discussed below). To declare a new variable the `var` keyword is used, followed by the name of the variable. It is possible to either immediately assign a value to the variable, or lazily assign a value. If no value is assigned, the variable will default to `null`.
- `var name = "Foo";` -> `"Foo"`
- `var name` -> `null`
- ```js
  var name;
  name = "Foo";
  ```

#### Conditional statements ✅
Conditions have partially been shown in the above specification for expressions, this section will further describe these expressions and their application in scripts. A condition is any expression that evaluates to a truthy value, which in turn is always evaluated into a `boolean` value. For the sake of simplicity, we will only use explicit `boolean` values in this section.

Using condition operators it is possible to easily construct complex conditions, which can be used to evaluate a specific code block only if a condition does (not) match. A common example of this is the `if`-statement. An `if`-statement consists of at least one condition, and a body (collection of statements) to execute if the condition evaluates to `true`.
```js
if (true) { 
    print("Hello world!")
}
```
`if`-statements can also hold `else` bodies, which are evaluated if the condition evaluates to `false`.
```js
if (true) {
    print("Hello foo!");
}
else {
    print("Hello bar!");
}
```
Additionally, it is possible to make use of `else-if` statements to add alternative bodies to the statement.
```js
if (true == false) {
    print("Hello foo!");
}
else if (true == true) {
    print("Hello bar!");
}
else {
    print("Hello baz!");
}
```

##### Repeat ✅
Repeat statements are the easiest method of repeating a single body `n` amount of times. The statement is simple, and accepts any expression yielding a valid number.
```js
repeat(10) {
   print("Repeat");
}
```
If required, it is also possible to break the loop early, using the `break` statement.
```js
repeat(10) {
    print("Repeat");
    break;
}
```

##### While ✅
A classic while loop statement, being exactly what you think it is. The body is executed as long as the given condition yields true, or until a `break` statement is called. If the condition yields false on the first iteration, the body is never executed.
```js
var i = 0;
while(i < 10){
   i = i + 1;
   print (i);
}
```

##### Do while ✅
Another classic, similar to the while loop statement but with the exception that the body is always executed at least once. If the condition yields false or a `break` statement is called the loop breaks.
```js
var i = 0;
do{
  i = i + 1;
  continue;
} while (i == 10);
```

##### For-each ✅
Utility `for` loop to iterate over all elements of a given `Iterable`. This allows you to perform the loop body for every element in the given collection. 
```js
for (var element in collection) {
    print(element);
}
```
The collection may be any expression returning a valid iterable:
```js
for (var number in [1, 2, 3]) {
    print(number);
}
```

##### Indexed for ✅
Classic `for` loop, to iterate while a specific condition is met. The `for` loop has three expressions:
- Initializer, to initialize a variable which will be available inside the loop body
- The condition to meet, which decides when the loop should continue or break
- Step action, the expression to execute after each iteration

A simple example is as follows:
```js
for (var i=0; i<10; i++) {
    print("Step " + i);
}
```

#### Standard blocks ✅
Standard/unnamed blocks are simple ways to define a local scope without a specific condition. These blocks are executed in the same order they are written.
```js
var x = 1;
{
    var y = 1;
    print(y);
    print(x);
}
print(y); // Error
print(x);
```

#### Functions ✅
(_Descriptions are only described briefly, as they are pending further improvement in #780_)
Functions allow you to move common code into a reusable block. Functions are not executed when they are defined, and only when they are called in otherwise executed code.
```js
fun count(n) {
  if (n > 1) {
     count(n - 1);
  }
  print(n);
}
count(3);
```
Functions can optionally return a value, if no value is explicitely returned, the default return value is `null`. It is also possible to reference a method without calling it directly, allowing it to be passed as a callback.
```js
fun username() {
    return "Foo";
}

fun greet(user) {
    print("Hello " + user());
}

var user = username;
greet(user);
```

#### Classes ✅
Classes allow you to describe methods which exist on a specific object instance. Due to classes being scheduled for expansion in #782 and #783, these will not be described here as the current implementation is primitive at best.

#### Assertions/testing ✅
Assertions allow you to save a result to the runtime, which can be inspected by the executing runtime. An assertion is marked by the `test` keyword, followed by the name of the assertion. The assertion itself is a single block body, which can contain any amount of statements, but has to end with a `return` statement indicating the result of the assertion. The return value is interpreted as _truthy_, and can thus be a non-boolean value.
```js
fun sum(x, y) {
   return x + y;
}

test ("test sum function") {
   return sum(1, 1) == 2;
}
```
Depending on the used `ResultCollector` the result of this assertion can then be inspected using the sample below. The use of result collectors will be further described in the **Runtimes** chapter below.
```java
ResultCollector collector = ...;
boolean passed = collector.result("test sum function"); // true | false
```

#### Infix and prefix ✅
Infix and prefix functions are stereotypes of standard functions. Their signature is similar to that of functions, with the addition of a `prefix` or `infix` keyword prepending the function declaration. 

Prefix functions can be invoked with a single argument, without the need for parentheses around the argument. It is however also possible to use prefix functions as usual. Prefix functions are limited to a single parameter per function.
```js
prefix fun multiByTen(x) {
   return x * 10;
}

print(multiByTen 10);
```

Infix functions are similar to prefix function in that they don't require parentheses to be used. Unlike prefix functions, infix functions accept two parameters, which are placed before and after the function name when the function is invoked. This allows  you to create more readable workflows in scripts. For example, to get a value, or a fallback in case the value is falsey:
```js
infix fun or(value, default) {
    return value ?: default;
}
var foo = null or "Bar" // "Bar"
var bar = "Foo" or "Bar" // "Foo"
```

#### Switch-case ✅
Switch statements allow you to pick specific side-effects based on the value of a given input. This requires only one expression, with literal values indicating the specific case branches.
```js
var name = ...;
switch (name) {
    case "Foo":
        print("Hello foo!");
    case "Bar":
        print("Hello bar!");
}
```
Note that case bodies do not need to end with a `break` statement, as fall-through is not possible in HSL. `break` statements can however still be used to break a case body early.
```js
var name = ...;
switch (name) {
    case "Foo":
        print("Hello foo!");
    case "Bar":
        print("Hello bar!");
        break;
        print("Hello again!"); // Unreachable
}
```
Additionally, it is possible to use single expressions in a shorthand manner, to make writing simple switch statements easier.
```js
var name = ...;
switch (name) {
    case "Foo" -> print("Hello foo!");
    case "Bar" -> print("Hello bar!");
}
```
Finally, it is also possible to handle all unspecified cases by using a `default` branch, which is selected when none of the case branches are matched.
```js
var name = "Baz";
switch (name) {
    case "Foo" -> print("Hello foo!");
    case "Bar" -> print("Hello bar!");
    default -> print("Hello other user!");
}
```

### Evaluation error handling ✅
Evaluation errors can occur during several phases of the script evaluation. To aid developers in tracing potential errors, HSL tracks the exact source position of every token. This allows errors to be traced back to a specific line and column position. When errors are handled by any implementation of `AbstractScriptRuntime`, the errors will be enhanced to display these positions. For example, the following snippet attempts to use an undefined variable `a`, which is reported and indicated by the error reporter.
```js
var b = 12;
var c = a + b;
```
```java
ScriptEvaluationError: Undefined variable 'a'. While interpreting at line 2, column 8.
var c = a + b;
        ^
```
The error immediately indicates at which phase the error occurred (tokenizing, parsing, resolving, or interpreting), and displays the position by indicating the explicit line and column number as well as visualizing this to show the content of the line and pinpointing the column where the error occurred.

For example, when using unknown tokens in your script, an error would occur while parsing, which is displayed in a similar manner.
```js
var b = 12;
var c @= b;
```
```java
ScriptEvaluationError: Unexpected character '@' while tokenizing at line 2, column 6.
var c @= b;
      ^
```

### Runtimes ✅
HSL comes with several pre-defined runtimes, which allow scripts to be customized during any of the afore mentioned phases. The `ScriptRuntime` allows for full customization of the script execution, the standard implementation for this interface is the `AbstractScriptRuntime`. Subtypes of the `AbstractScriptRuntime` include the `StandardRuntime` which includes standard libraries as defined in the `StandardLibrary` enum, and the `ValidateExpressionRuntime` which applies a customizer to wrap the script body in a `test` statement to run the script as a standalone assertion.

The `ScriptRuntime` however requires some level of configuration, and is only optimized to ease the control flow of script evaluation. On top of the `ScriptRuntime` there is also the `HslScript` type, which allows you to load a script from various sources including `String`s, `Path`s, and `File`s. The advantage of a `HslScript` is that it uses caching to only resolve once, allowing future evaluations to only require interpretation. 

The `HslScript` exposes the underlying `ScriptRuntime`, to allow the same level of customization. Additionally, it also exposes a `ScriptContext` which tracks results and available components (including tokens, statements, comments, and the executors for each evaluation phase).

Closes #770

## Type of change
- [x] New feature (non-breaking change that does affect the code)

# How Has This Been Tested?
- [x] Unit testing
- [x] Integration testing
- [x] Manual testing

# Checklist:
- [x] I have performed a self-review of my own code
- [x] I have added tests that prove it is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Related issue number is linked in pull request title

### CODE REVIEW

**Comment by GuusLieben** [comment]
## Pending specification/implementation
### Typed variables
Expansion of variable declarations, to allow adding a type constraint to variables. Possible solutions (in order of preference);
- `var name: String = "Foo"`
- `String name = "Foo"`
- `var(String) name = "Foo"`

### Final values
Expansion of variable declarations and parameters, to disallow the re-assignment of variables. This should be possible at least on the declaration of a variable, and potentially at specific evaluation steps. Potential approaches to final declarations (in order of preference):
- `const name = "Foo"`
- `val name = "Foo"`
- `final var name = "Foo"`

Optional addition to lock during evaluation step:
- ```js
  var name;
  name = final "Foo";
  ```
- ```js
  lazy const name; // const interchangeable with 'val' or 'final var', depending on decision above
  name = "Foo";
  ```
- ```js
  var name;
  name = "Foo";
  lock(name);
  ```

### `ForStatement`
Standard `for` loop, to iterate while a specific condition is met (`for-i`) or to iterate over a collection/array (`for-each`). Standard `for` loop should follow the common notation of `variables; condition; step action`. 
```js
for (var i = 0; i < 10; i++) {
    print("Step " + i);
}
```
For-each loops can use a specific syntax to indicate the loop iterates over a specific collection, potential options are (in order of preference):
```js
for (var x in arr) { ... }
```
```js
for (var x : arr) { ... }
```
```js
foreach (var x OP arr) { ... } // OP being either 'in' or ':'
```

### Support for 'get and increment/decrement'
Currently it is only possible to increment/decrement, and get the resulting value afterwards (`++i`, `--i`). While this is technically fine, it would be nice to also support 'get and increment/decrement` (`i++`, `i--`)

**Comment by pumbas600** [comment]
### Operator Overloading

One of the things I love about `C#` is the ability to override the default operators to add support for custom classes. This potentially could be done using something similar to how you define `infix`s above.

**Comment by pumbas600** [comment]
### Operator Overloading

One cool feature from C# is the ability to override operators to support your custom classes, allowing for more apparent software.

### Standard Library

An expansion which, among other things would include utility types like `List`.

### List Comprehension

Python list comprehension allows you to create lists in a way that is concise and easy to follow and understand. This would likely be using Arrays for HSL.

The general form of a comprehension is:
```py
newlist = [expression for item in iterable if condition == True]
```

#### Some examples:
- Copy a list
```py
original = [1, 2, 3]
copy = [x for x in original]
```

- Create a new list with only even numbers
```py
original = [1, 2, 3]
copy = [x for x in original if x % 2 == 0]
```

- Create a new list with the reciprocal of each number
 ```py
original = [1, 2, 3]
# Notice how when x is 0, `0` is used rather than `1/x` to prevent a divide by 0 error
copy = [1/x for x in original if x != 0 else 0]
```

- Create a list of integers from the next 30 inputs from the user:
```py
inputs = [int(input()) for _ in range(30)]
```

**Comment by GuusLieben** [comment]
Nice additions, will add these to the schedule. List comprehension may be reserved for a future PR, but would like to add these to HSL. Some additions:

### Operator Overloading
Potential syntax:
```js
class TheObject {
    operator fun ++() { ... } // Unary operators
    operator fun +(other) { ... } // Binary/logical operators
}
```
Both functions would require a return value, would also be nice to integrate this with type declarations, so it is possible to limit the accepted `other` parameter types (and reject at evaluation if an argument is invalid, either during resolving (if possible) or at interpretation).

### List comprehension
Your examples (rightfully) give examples using arrays, the last one however drew some attention:
```js
inputs = [int(input()) for _ in range(30)]
```
It may be nice to be able to integrate this with `repeat(x)` so you don't need to use unnamed arguments:
```js
inputs = [int(input()) for repeat(30)]
```

**Comment by pumbas600** [comment]
> It may be nice to be able to integrate this with `repeat(x)` so you don't need to use unnamed arguments

That is definitely nicer! It's also all in python syntax, but it seems to mostly fit with HSL :)

**Comment by GuusLieben** [comment]
> ```js
> original = [0, 1, 2, 3]
> copy = [x for x in original if x % 2 == 0]
> # copy = [0, 2]
> ```

This reminds me, HSL doesn't have a modulo operator yet.
- [ ] Implement modulo operator

**Pull request merged**
